#!/bin/bash          
echo Ensure 'classes' directory exists
mkdir classes
echo Compile 'purejavacomm'
javac -d classes -sourcepath ./src -cp lib/jna-4.0.0.jar src/purejavacomm/testsuite/TestSuite.java -Xlint:deprecation

